[build]
  publish = "public"
  command = "hugo --minify"

[context.production.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
  X-Frame-Options = "DENY"

  Content-Security-Policy = '''
	default-src 
  'self'
  '''

  cache-control = '''
	max-age=3600,
	public'''
